builds:
  - id: "my-build"
    env:
    - GOPRIVATE=github.com/Khan
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
    ldflags:
    - -s
    - -w
    - -extldflags "-static"
    - -X github.com/Khan/districts-jobs/pkg/version.AppName={{.Env.APP}}
    - -X github.com/Khan/districts-jobs/pkg/version.Date={{.Env.BUILD_DATE}}
    - -X github.com/Khan/districts-jobs/pkg/version.GitCommit={{.Env.COMMIT_SHA}}
    - -X github.com/Khan/districts-jobs/pkg/version.Version={{.Env.VERSION}}
    - -X github.com/Khan/districts-jobs/pkg/version.Project={{.Env.PROJECT}}
# ko publish --bare -t latest -t "$COMMIT_SHA" .
# PLATFORM="linux/amd64,linux/arm64,linux/386,linux/arm"

